/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: aaflak6443 (https://sketchfab.com/aaflak6443)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/maserati-quattroporte-2019-090cb9abe4bf4c268d8c10a04a0de6b8
title: Maserati Quattroporte 2019
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Car(props) {
    const { nodes, materials } = useGLTF('../../public/models/car/model-transformed.glb')
    return (
        <group {...props} dispose={null}>
            <group rotation={[-Math.PI / 2, 0, 0]}>
                <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
                    <group position={[0, 0, 14.33]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.GEO_underside_SUB0_EXT_underside_0.geometry} material={materials['INT_speaker_metal.2']} />
                    </group>
                    <group position={[0, 0, 14.45]}>
                        <group position={[36.82, 96.45, 56.43]} rotation={[-Math.PI / 2, 0, 0]} scale={0.41}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_displays_004_2_INT_display_0.geometry} material={materials['INT_display.10']} />
                        </group>
                        <group position={[36.82, 94.8, 56.4]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_gauges_001_2_INT_decals_0.geometry} material={materials['INT_decals.4']} />
                        </group>
                        <group position={[26.55, 94.29, 55.56]} rotation={[0.38, 0, 0.36]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_gauges_002_2_INT_decals1_0.geometry} material={materials['INT_decals.4']} />
                        </group>
                        <group position={[36.95, 95.22, 55.75]} rotation={[-Math.PI / 2, 0, -0.01]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_displays_003_2_INT_decals_emissive_0.geometry} material={materials['INT_plastic_nodet.10']} />
                        </group>
                        <group position={[36.81, 91.62, 54.62]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.IND_LIGHT_2_INT_decals2_0.geometry} material={materials['INT_decals.4']} />
                        </group>
                        <group position={[36.81, 91.62, 54.62]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.IND_FUEL_2_INT_decals3_0.geometry} material={materials['INT_decals.4']} />
                        </group>
                        <group position={[36.82, 94.91, 55.62]} rotation={[-1.6, 0, 0.01]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_displays_001_2_INT_display1_0.geometry} material={materials['INT_display.10']} />
                        </group>
                        <group rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_interiors_at_SUB2_INT_logo_0.geometry} material={materials.INT_logo} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_interiors_at_SUB0_INT_seam2_0.geometry} material={materials['INT_plastic_nodet.10_0']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_interiors_at_SUB1_INT_seam_0.geometry} material={materials.INT_seam} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_interiors_at_SUB3_INT_decals4_0.geometry} material={materials['INT_decals.4']} />
                        </group>
                        <group position={[36.82, 94.8, 56.4]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_gauges_2_INT_decals5_0.geometry} material={materials['INT_decals.4']} />
                        </group>
                        <group rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_mirrorC_2_EXT_mirrors_0.geometry} material={materials.EXT_mirrors} />
                        </group>
                        <group position={[0, 0, 35.63]} rotation={[Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_interiors_det_SUB8_INT_belts_0.geometry} material={materials.INT_belts} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_interiors_det_SUB5_INT_speaker_0.geometry} material={materials['EXT_headlight_chrome.6']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_interiors_det_SUB9_INT_pedals_0.geometry} material={materials['INT_speaker_metal.2_0']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_interiors_det_SUB4_INT_speaker_metal_0.geometry} material={materials['INT_speaker_metal.2_1']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_interiors_det_SUB6_INT_metal_black_0.geometry} material={materials.INT_logo_steer} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_interiors_det_SUB3_INT_metal_0.geometry} material={materials['INT_metal.8']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_interiors_det_SUB1_INT_plastic_nodet_red_0.geometry} material={materials.INT_plastic_nodet_red} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_interiors_det_SUB0_INT_plastic_nodet_0.geometry} material={materials['INT_plastic_nodet.10_1']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_interiors_det_SUB7_INT_rubber_0.geometry} material={materials['INT_rubber.2']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_interiors_det_SUB2_INT_frames_0.geometry} material={materials['INT_frames.1']} />
                        </group>
                        <group position={[0, 0, 35.63]} rotation={[Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_watch_2_INT_decals6_0.geometry} material={materials['INT_decals.4']} />
                        </group>
                        <group position={[0, 0, 35.63]} rotation={[Math.PI / 2, 0, 0]}>
                            <group position={[20.15, 9.89, -88.64]}>
                                <mesh castShadow receiveShadow geometry={nodes.GEO_interiors_glass_2_INT_glass_0.geometry} material={materials.EXT_headlight_glass} />
                            </group>
                        </group>
                        <group rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.CINTURE_ON_SUB1_INT_metal1_0.geometry} material={materials['INT_metal.8']} />
                            <mesh castShadow receiveShadow geometry={nodes.CINTURE_ON_SUB0_INT_plastic_nodet1_0.geometry} material={materials['INT_plastic_nodet.10_1']} />
                        </group>
                        <group position={[36.82, 94.76, 56.46]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_gaugesBG_2_INT_gauges_0.geometry} material={materials['EXT_tyre.2']} />
                        </group>
                        <group position={[0.1, 0, 35.63]} rotation={[-Math.PI / 2, 0, 0]} scale={0.41}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_displays_2_INT_display2_0.geometry} material={materials['INT_display.10']} />
                        </group>
                        <group position={[0, 0, 35.63]} rotation={[Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_interiors_SUB5_INT_carpet_0.geometry} material={materials.INT_carpet} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_interiors_SUB3_INT_alcnt_0.geometry} material={materials.INT_alcnt} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_interiors_SUB0_INT_leather_color_0.geometry} material={materials.INT_leather_color} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_interiors_SUB2_INT_leather_0.geometry} material={materials['INT_leather.1']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_interiors_SUB1_INT_plastic_0.geometry} material={materials['INT_leather.1_0']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_interiors_SUB4_INT_plastic_color_0.geometry} material={materials.INT_plastic_color} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_interiors_SUB6_INT_carbon_0.geometry} material={materials['INT_carbon.4']} />
                        </group>
                        <group position={[46.29, 86.76, 37.37]} rotation={[0.38, 0, -0.01]} scale={0.09}>
                            <group position={[-112.51, 11.02, -2.57]} rotation={[-1.95, -0.01, 0.01]} scale={11.7}>
                                <mesh castShadow receiveShadow geometry={nodes.GEO_shiftDw_2_INT_carbon1_0.geometry} material={materials['INT_carbon.4']} />
                            </group>
                        </group>
                        <group position={[26.83, 86.89, 37.03]} rotation={[0.38, 0, -0.01]} scale={0.09}>
                            <group position={[115.24, 11.02, -2.57]} rotation={[-1.95, -0.01, 0.01]} scale={11.7}>
                                <mesh castShadow receiveShadow geometry={nodes.GEO_shiftUp_2_INT_carbon2_0.geometry} material={materials['INT_carbon.4']} />
                            </group>
                        </group>
                        <group position={[26.55, 94.29, 55.56]} rotation={[0.38, 0, 0.79]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_arrowRPM_light_2_INT_plastic_nodet2_0.geometry} material={materials['INT_plastic_nodet.10_1']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_arrowRPM_SUB1_INT_metal2_0.geometry} material={materials['INT_metal.8']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_arrowRPM_SUB0_INT_plastic_nodet3_0.geometry} material={materials['INT_plastic_nodet.10_1']} />
                        </group>
                        <group position={[37.34, 91.06, 58.13]} rotation={[0.39, 0, 0]}>
                            <group position={[-0.44, 2.69, -3.62]} rotation={[-1.98, 0, 0.01]}>
                                <mesh castShadow receiveShadow geometry={nodes.TAG_WATER_0_2_INT_display3_0.geometry} material={materials['INT_display.10']} />
                            </group>
                            <group position={[-0.44, 2.69, -3.62]} rotation={[-1.98, 0, 0.01]}>
                                <mesh castShadow receiveShadow geometry={nodes.TAG_WATER_1_2_INT_display4_0.geometry} material={materials['INT_display.10']} />
                            </group>
                            <group position={[-0.44, 2.69, -3.62]} rotation={[-1.98, 0, 0.01]}>
                                <mesh castShadow receiveShadow geometry={nodes.TAG_WATER_2_2_INT_display5_0.geometry} material={materials['INT_display.10']} />
                            </group>
                            <group position={[-0.44, 2.69, -3.62]} rotation={[-1.98, 0, 0.01]}>
                                <mesh castShadow receiveShadow geometry={nodes.TAG_WATER_3_2_INT_display6_0.geometry} material={materials['INT_display.10']} />
                            </group>
                            <group position={[-0.44, 2.69, -3.62]} rotation={[-1.98, 0, 0.01]}>
                                <mesh castShadow receiveShadow geometry={nodes.TAG_WATER_4_2_INT_display7_0.geometry} material={materials['INT_display.10']} />
                            </group>
                            <group position={[-0.44, 2.69, -3.62]} rotation={[-1.98, 0, 0.01]}>
                                <mesh castShadow receiveShadow geometry={nodes.TAG_WATER_5_2_INT_display8_0.geometry} material={materials['INT_display.10']} />
                            </group>
                            <group position={[-0.44, 2.69, -3.62]} rotation={[-1.98, 0, 0.01]}>
                                <mesh castShadow receiveShadow geometry={nodes.TAG_WATER_6_2_INT_display9_0.geometry} material={materials['INT_display.10']} />
                            </group>
                            <group position={[-0.44, 2.69, -3.62]} rotation={[-1.98, 0, 0.01]}>
                                <mesh castShadow receiveShadow geometry={nodes.TAG_WATER_7_2_INT_display10_0.geometry} material={materials['INT_display.10']} />
                            </group>
                            <group position={[-0.44, 2.69, -3.62]} rotation={[-1.98, 0, 0.01]}>
                                <mesh castShadow receiveShadow geometry={nodes.TAG_FUEL_7_2_INT_display11_0.geometry} material={materials['INT_display.10']} />
                            </group>
                            <group position={[-0.44, 2.69, -3.62]} rotation={[-1.98, 0, 0.01]}>
                                <mesh castShadow receiveShadow geometry={nodes.TAG_FUEL_6_2_INT_display12_0.geometry} material={materials['INT_display.10']} />
                            </group>
                            <group position={[-0.44, 2.69, -3.62]} rotation={[-1.98, 0, 0.01]}>
                                <mesh castShadow receiveShadow geometry={nodes.TAG_FUEL_5_2_INT_display13_0.geometry} material={materials['INT_display.10']} />
                            </group>
                            <group position={[-0.44, 2.69, -3.62]} rotation={[-1.98, 0, 0.01]}>
                                <mesh castShadow receiveShadow geometry={nodes.TAG_FUEL_4_2_INT_display14_0.geometry} material={materials['INT_display.10']} />
                            </group>
                            <group position={[-0.44, 2.69, -3.62]} rotation={[-1.98, 0, 0.01]}>
                                <mesh castShadow receiveShadow geometry={nodes.TAG_FUEL_3_2_INT_display15_0.geometry} material={materials['INT_display.10']} />
                            </group>
                            <group position={[-0.44, 2.69, -3.62]} rotation={[-1.98, 0, 0.01]}>
                                <mesh castShadow receiveShadow geometry={nodes.TAG_FUEL_2_2_INT_display16_0.geometry} material={materials['INT_display.10']} />
                            </group>
                            <group position={[-0.44, 2.69, -3.62]} rotation={[-1.98, 0, 0.01]}>
                                <mesh castShadow receiveShadow geometry={nodes.TAG_FUEL_1_2_INT_display17_0.geometry} material={materials['INT_display.10']} />
                            </group>
                            <group position={[-0.44, 2.69, -3.62]} rotation={[-1.98, 0, 0.01]}>
                                <mesh castShadow receiveShadow geometry={nodes.TAG_FUEL_0_2_INT_display18_0.geometry} material={materials['INT_display.10']} />
                            </group>
                        </group>
                        <group position={[47.09, 94.29, 55.54]} rotation={[0.38, 0, 0.79]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_arrowSpeed_light_2_INT_plastic_nodet4_0.geometry} material={materials['INT_plastic_nodet.10_1']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_arrowSpeed_SUB1_INT_metal3_0.geometry} material={materials['INT_metal.8']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_arrowSpeed_SUB0_INT_plastic_nodet5_0.geometry} material={materials['INT_plastic_nodet.10_1']} />
                        </group>
                        <group position={[-80.25, 69.64, 70.4]} rotation={[0, 0.31, 0]}>
                            <group rotation={[-Math.PI / 2, 0, 0.02]} scale={0.04}>
                                <mesh castShadow receiveShadow geometry={nodes.GEO_doorR_arm_2_INT_plastic_nodet6_0.geometry} material={materials['INT_plastic_nodet.10_1']} />
                            </group>
                        </group>
                        <group position={[80.25, 69.64, 70.4]} rotation={[0, -0.31, 0]}>
                            <group rotation={[-Math.PI / 2, 0, 0]} scale={0.04}>
                                <mesh castShadow receiveShadow geometry={nodes.GEO_doorL_arm_2_INT_plastic_nodet7_0.geometry} material={materials['INT_plastic_nodet.10_1']} />
                            </group>
                        </group>
                        <group position={[36.72, 87.32, 39.11]} rotation={[0.38, -0.02, 0]}>
                            <group position={[0, 0, -0.14]}>
                                <mesh castShadow receiveShadow geometry={nodes.GEO_steer_at_SUB2_INT_logo_steer_0.geometry} material={materials.INT_logo_steer_0} />
                                <mesh castShadow receiveShadow geometry={nodes.GEO_steer_at_SUB1_INT_seam1_0.geometry} material={materials.INT_seam} />
                                <mesh castShadow receiveShadow geometry={nodes.GEO_steer_at_SUB0_INT_decals7_0.geometry} material={materials['INT_decals.4']} />
                            </group>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_steer_det_SUB1_INT_metal4_0.geometry} material={materials['INT_metal.8']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_steer_det_SUB0_INT_plastic_nodet8_0.geometry} material={materials['INT_plastic_nodet.10_1']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_steer_SUB1_INT_carbon_wheel_0.geometry} material={materials['INT_carbon.4']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_steer_SUB0_INT_leather2_wheel_0.geometry} material={materials.INT_leather2_wheel} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_steer_SUB2_INT_leather_wheel_0.geometry} material={materials.INT_leather_wheel} />
                        </group>
                        <group rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.CINTURE_OFF_SUB0_INT_belts1_0.geometry} material={materials.INT_belts} />
                            <mesh castShadow receiveShadow geometry={nodes.CINTURE_OFF_SUB2_INT_metal5_0.geometry} material={materials['INT_metal.8']} />
                            <mesh castShadow receiveShadow geometry={nodes.CINTURE_OFF_SUB1_INT_plastic_nodet9_0.geometry} material={materials['INT_plastic_nodet.10_1']} />
                        </group>
                        <group position={[36.9, 94.93, 55.86]} rotation={[-1.6, 0, 0.01]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_displays_002_2_INT_display19_0.geometry} material={materials['INT_display.10']} />
                        </group>
                    </group>
                    <group position={[0, 0, 14.45]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.REAR_LIGHT_3_2_EXT_rearlight_chrome_0.geometry} material={materials.EXT_rearlight_chrome} />
                    </group>
                    <group position={[0, 0, 14.45]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.REAR_LIGHT_1_2_EXT_rearlight_chrome1_0.geometry} material={materials.EXT_rearlight_chrome} />
                    </group>
                    <group position={[0, 0, 14.45]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.FRONT_LIGHT_4_2_EXT_headlight_chrome_0.geometry} material={materials['EXT_headlight_chrome.6_0']} />
                    </group>
                    <group position={[4.02, 43, 239.29]}>
                        <group position={[-4.02, -43, -224.84]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.g_Grille_4_2_EXT_plastic_0.geometry} material={materials['EXT_plastic.11']} />
                        </group>
                    </group>
                    <group position={[4.02, 47.02, 239.29]}>
                        <group position={[-4.02, -47.02, -224.84]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.g_Grille_3_2_EXT_plastic1_0.geometry} material={materials['EXT_plastic.11']} />
                        </group>
                    </group>
                    <group position={[4.02, 51.05, 239.29]}>
                        <group position={[-4.02, -51.05, -224.84]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.g_Grille_2_2_EXT_plastic2_0.geometry} material={materials['EXT_plastic.11']} />
                        </group>
                    </group>
                    <group position={[4.02, 55.08, 239.29]}>
                        <group position={[-4.02, -55.08, -224.84]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.g_Grille_1_2_EXT_plastic3_0.geometry} material={materials['EXT_plastic.11']} />
                        </group>
                    </group>
                    <group position={[22.45, 92.56, 129.72]} rotation={[-1.07, 0.08, -0.49]}>
                        <group position={[-15.19, 0.16, -0.87]} rotation={[0.15, -0.01, 0.29]}>
                            <group position={[-14.83, 28.62, -142.05]} rotation={[-0.62, -0.12, 0.16]}>
                                <mesh castShadow receiveShadow geometry={nodes.GEO_wiper_5_2_EXT_plastic4_0.geometry} material={materials['EXT_plastic.11']} />
                            </group>
                            <group position={[-61.59, 3.32, -8.61]} rotation={[-0.02, -0.21, -0.17]}>
                                <group position={[13.63, 30.78, -139.64]} rotation={[-0.6, -0.05, 0.42]}>
                                    <mesh castShadow receiveShadow geometry={nodes.GEO_wiper_6_2_EXT_plastic5_0.geometry} material={materials['EXT_plastic.11']} />
                                </group>
                            </group>
                        </group>
                        <group position={[-36.78, 43.84, -138.14]} rotation={[-0.43, -0.29, 0.41]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_wiper_4_2_EXT_plastic6_0.geometry} material={materials['EXT_plastic.11']} />
                        </group>
                    </group>
                    <group position={[0, 0, 14.45]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.GEO_underside_radiators_2_EXT_radiator_0.geometry} material={materials.EXT_radiator} />
                    </group>
                    <group position={[0, 0, 14.45]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.GEO_body_carpaint_2_EXT_carpaint_0.geometry} material={materials['EXT_carpaint.2']} />
                    </group>
                    <group position={[0, 0, 14.45]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.GEO_body_2_EXT_carpaint1_0.geometry} material={materials['EXT_carpaint.2']} />
                    </group>
                    <group position={[0, 0, 14.45]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.FRONT_LIGHT_5_2_EXT_headlight_chrome1_0.geometry} material={materials['EXT_headlight_chrome.6_0']} />
                    </group>
                    <group position={[0, 0, 14.45]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.FRONT_LIGHT_3_2_EXT_headlight_chrome2_0.geometry} material={materials['EXT_headlight_chrome.6_0']} />
                    </group>
                    <group position={[0, 0, 14.45]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.FRONT_LIGHT_2_2_EXT_headlight_chrome3_0.geometry} material={materials['EXT_headlight_chrome.6_0']} />
                    </group>
                    <group position={[0, 0, 14.45]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.GEO_logos_chromed_2_EXT_chrome_0.geometry} material={materials['EXT_headlight_chrome.6_1']} />
                    </group>
                    <group position={[0, 0, 14.45]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.GEO_exhausts_2_EXT_exhaust_0.geometry} material={materials['EXT_rim.1']} />
                    </group>
                    <group position={[0, 0, 14.45]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.GEO_body_glasses_2_EXT_glass_0.geometry} material={materials.EXT_headlight_glass} />
                    </group>
                    <group position={[0, 0, 14.45]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.FRONT_LIGHT_1_2_EXT_headlight_chrome4_0.geometry} material={materials['EXT_headlight_chrome.6_0']} />
                    </group>
                    <group position={[0, 0, 14.45]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.GEO_headlight_subglass_2_EXT_headlight_glass_0.geometry} material={materials.EXT_headlight_glass} />
                    </group>
                    <group position={[0, 0, 14.45]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.GEO_headlight_SUB0_EXT_headlight_chrome5_0.geometry} material={materials['EXT_headlight_chrome.6_0']} />
                        <mesh castShadow receiveShadow geometry={nodes.GEO_headlight_SUB1_EXT_headlight_chrome_satin_0.geometry} material={materials.EXT_headlight_chrome_satin} />
                        <mesh castShadow receiveShadow geometry={nodes.GEO_headlight_SUB2_EXT_headlight_plastic_0.geometry} material={materials.EXT_headlight_plastic} />
                    </group>
                    <group position={[0, 0, 14.45]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.GEO_rearlight_subglass_2_EXT_rearlight_glass_0.geometry} material={materials['EXT_rearlight_glass.1']} />
                    </group>
                    <group position={[0, 0, 14.45]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.REAR_LIGHT_2_2_EXT_rearlight_0.geometry} material={materials['INT_carbon.4_0']} />
                    </group>
                    <group position={[0, 0, 14.45]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.GEO_rearlight_2_EXT_rearlight_chrome2_0.geometry} material={materials.EXT_rearlight_chrome} />
                    </group>
                    <group position={[0, 0, 14.45]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.GEO_body_sidegrille_2_EXT_side_grille_0.geometry} material={materials['EXT_headlight_chrome.6_2']} />
                    </group>
                    <group position={[0, 0, 14.45]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.GEO_underside_SUB1_EXT_plastic7_0.geometry} material={materials['EXT_plastic.11']} />
                        <mesh castShadow receiveShadow geometry={nodes.GEO_underside_SUB0_2_EXT_underside_0.geometry} material={materials['INT_speaker_metal.2']} />
                    </group>
                    <group position={[0, 0, 14.45]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.GEO_body_frontgrille_2_EXT_front_grille2_0.geometry} material={materials['INT_plastic_nodet.10_2']} />
                    </group>
                    <group position={[0, 0, 14.45]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.GEO_body_chrome_SUB1_EXT_carbonfiber_0.geometry} material={materials.EXT_carbonfiber} />
                        <mesh castShadow receiveShadow geometry={nodes.GEO_body_chrome_SUB0_EXT_chrome1_0.geometry} material={materials['EXT_headlight_chrome.6_1']} />
                    </group>
                    <group position={[-87.13, 69.36, 88.52]}>
                        <group position={[87.13, -69.5, 22.79]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorR_carpaint_SUB1_INT_carpaint_0.geometry} material={materials.INT_carpaint} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorR_carpaint_SUB0_INT_metal6_0.geometry} material={materials['INT_metal.8']} />
                        </group>
                        <group position={[87.13, -69.5, 22.79]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorR_det_SUB1_INT_speaker1_0.geometry} material={materials['EXT_headlight_chrome.6']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorR_det_SUB3_INT_speaker_metal1_0.geometry} material={materials['INT_speaker_metal.2_1']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorR_det_SUB4_INT_metal7_0.geometry} material={materials['INT_metal.8']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorR_det_SUB0_INT_plastic_nodet10_0.geometry} material={materials['INT_plastic_nodet.10_1']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorR_det_SUB2_INT_rubber1_0.geometry} material={materials['INT_rubber.2']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorR_det_SUB5_INT_frames1_0.geometry} material={materials['INT_frames.1']} />
                        </group>
                        <group position={[87.13, -69.5, -74.07]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorR_windscreen_2_INT_windscreen_0.geometry} material={materials.INT_windscreen} />
                        </group>
                        <group position={[87.13, -69.5, 22.79]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorR_SUB0_INT_leather_color1_0.geometry} material={materials.INT_leather_color} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorR_SUB1_INT_leather1_0.geometry} material={materials['INT_leather.1_1']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorR_SUB2_INT_plastic1_0.geometry} material={materials['INT_leather.1_0']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorR_SUB3_INT_carbon3_0.geometry} material={materials['INT_carbon.4']} />
                        </group>
                        <group position={[87.13, -69.5, 22.79]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorR_at_SUB0_INT_seam2_0.geometry} material={materials.INT_seam} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorR_at_SUB1_INT_decals8_0.geometry} material={materials['INT_decals.4']} />
                        </group>
                        <group position={[87.13, -69.5, -74.07]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_sidelightR_chrome_2_EXT_headlight_chrome6_0.geometry} material={materials['EXT_headlight_chrome.6_0']} />
                        </group>
                        <group position={[87.13, -69.5, -74.07]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_mirrorR_2_EXT_mirrors1_0.geometry} material={materials.EXT_mirrors} />
                        </group>
                        <group position={[87.13, -69.5, -74.07]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorR_sidelight_glass_2_EXT_headlight_glass1_0.geometry} material={materials.EXT_headlight_glass} />
                        </group>
                        <group position={[87.13, -69.5, -74.07]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_body_doorR_SUB1_EXT_carbonfiber_0.geometry} material={materials.EXT_carbonfiber} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_body_doorR_SUB2_EXT_chrome2_0.geometry} material={materials['EXT_headlight_chrome.6_1']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_body_doorR_SUB0_EXT_plastic8_0.geometry} material={materials['EXT_plastic.11']} />
                        </group>
                        <group position={[87.13, -69.5, -74.07]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_body_doorR_carpaint_2_EXT_carpaint2_0.geometry} material={materials['EXT_carpaint.2']} />
                        </group>
                        <group position={[87.13, -69.5, -74.07]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorR_glass_2_EXT_glass1_0.geometry} material={materials.EXT_headlight_glass} />
                        </group>
                    </group>
                    <group position={[87.13, 69.36, 88.52]}>
                        <group position={[-87.13, -69.5, 22.79]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorL_carpaint_SUB1_INT_carpaint1_0.geometry} material={materials.INT_carpaint} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorL_carpaint_SUB0_INT_metal8_0.geometry} material={materials['INT_metal.8']} />
                        </group>
                        <group position={[-87.13, -69.5, -74.07]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorL_windscreen_2_INT_windscreen1_0.geometry} material={materials.INT_windscreen} />
                        </group>
                        <group position={[-87.13, -69.5, 22.79]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorL_at_SUB0_INT_seam3_0.geometry} material={materials.INT_seam} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorL_at_SUB1_INT_decals9_0.geometry} material={materials['INT_decals.4']} />
                        </group>
                        <group position={[-87.13, -69.5, 22.79]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorL_det_SUB0_INT_speaker2_0.geometry} material={materials['EXT_headlight_chrome.6']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorL_det_SUB3_INT_speaker_metal2_0.geometry} material={materials['INT_speaker_metal.2_1']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorL_det_SUB4_INT_metal9_0.geometry} material={materials['INT_metal.8']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorL_det_SUB2_INT_plastic_nodet11_0.geometry} material={materials['INT_plastic_nodet.10_1']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorL_det_SUB1_INT_rubber2_0.geometry} material={materials['INT_rubber.2']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorL_det_SUB5_INT_frames2_0.geometry} material={materials['INT_frames.1']} />
                        </group>
                        <group position={[-87.13, -69.5, 22.79]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorL_SUB1_INT_leather_color2_0.geometry} material={materials.INT_leather_color} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorL_SUB0_INT_leather2_0.geometry} material={materials['INT_leather.1_1']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorL_SUB2_INT_plastic2_0.geometry} material={materials['INT_leather.1_0']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorL_SUB4_INT_plastic_color1_0.geometry} material={materials.INT_plastic_color} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorL_SUB3_INT_carbon4_0.geometry} material={materials['INT_carbon.4']} />
                        </group>
                        <group position={[-87.13, -69.5, -74.07]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_sidelightL_chrome_2_EXT_headlight_chrome7_0.geometry} material={materials['EXT_headlight_chrome.6_0']} />
                        </group>
                        <group position={[-87.13, -69.5, -74.07]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorL_glass_2_EXT_glass2_0.geometry} material={materials.EXT_headlight_glass} />
                        </group>
                        <group position={[-87.13, -69.5, -74.07]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_body_doorL_carpaint_2_EXT_carpaint3_0.geometry} material={materials['EXT_carpaint.2']} />
                        </group>
                        <group position={[-87.13, -69.5, -74.07]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_mirrorL_2_EXT_mirrors2_0.geometry} material={materials.EXT_mirrors} />
                        </group>
                        <group position={[-87.13, -69.5, -74.07]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_doorL_sidelight_glass_2_EXT_headlight_glass2_0.geometry} material={materials.EXT_headlight_glass} />
                        </group>
                        <group position={[-87.13, -69.5, -74.07]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_body_doorL_SUB1_EXT_carbonfiber_0.geometry} material={materials.EXT_carbonfiber} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_body_doorL_SUB2_EXT_chrome3_0.geometry} material={materials['EXT_headlight_chrome.6_1']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_body_doorL_SUB0_EXT_plastic9_0.geometry} material={materials['EXT_plastic.11']} />
                        </group>
                    </group>
                    <group position={[66.87, 92.44, 118.09]} rotation={[-1.03, 0.14, -0.3]}>
                        <group position={[-58.21, 25.33, -140.45]} rotation={[-0.49, -0.27, 0.2]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_wiper_1_2_EXT_plastic10_0.geometry} material={materials['EXT_plastic.11']} />
                        </group>
                        <group position={[-15.19, 0.16, -0.87]} rotation={[0.15, -0.01, 0.2]}>
                            <group position={[-44.93, -2.01, -1.88]} rotation={[-0.02, -0.05, 0.21]}>
                                <group position={[-0.48, 18.43, -139.25]} rotation={[-0.65, 0.03, -0.1]}>
                                    <mesh castShadow receiveShadow geometry={nodes.GEO_wiper_3_2_EXT_plastic11_0.geometry} material={materials['EXT_plastic.11']} />
                                </group>
                            </group>
                            <group position={[-42.09, 13.19, -141.49]} rotation={[-0.67, -0.14, 0.04]}>
                                <mesh castShadow receiveShadow geometry={nodes.GEO_wiper_2_2_EXT_plastic12_0.geometry} material={materials['EXT_plastic.11']} />
                            </group>
                        </group>
                    </group>
                    <group position={[0, 67.84, -220.09]}>
                        <group position={[0, -67.84, 234.54]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_rbumper_carpaint_2_EXT_carpaint4_0.geometry} material={materials['EXT_carpaint.2']} />
                        </group>
                        <group position={[0, -67.84, 234.54]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_rbumper_grille_2_EXT_rear_grille_0.geometry} material={materials['INT_plastic_nodet.10_3']} />
                        </group>
                        <group position={[0, -67.84, 234.54]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_rbumper_light_glass_2_EXT_rearlight_glass1_0.geometry} material={materials['EXT_rearlight_glass.1']} />
                        </group>
                        <group position={[0, -67.84, 234.54]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_rbumper_SUB3_EXT_chrome_blue_0.geometry} material={materials['EXT_chrome_blue.3']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_rbumper_SUB2_EXT_rearlight_chrome3_0.geometry} material={materials.EXT_rearlight_chrome} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_rbumper_SUB1_EXT_metal_0.geometry} material={materials['EXT_metal.1']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_rbumper_SUB0_EXT_underside1_0.geometry} material={materials['INT_speaker_metal.2']} />
                        </group>
                    </group>
                    <group position={[0, 97.27, 106.9]}>
                        <group position={[0, -97.27, -92.45]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_body_hood_2_EXT_underside2_0.geometry} material={materials['INT_speaker_metal.2']} />
                        </group>
                        <group position={[0, -97.27, -92.45]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_body_hood_carpaint_2_EXT_carpaint5_0.geometry} material={materials['EXT_carpaint.2']} />
                        </group>
                    </group>
                    <group position={[0, 65.97, 234.63]}>
                        <group position={[0, -65.97, -220.18]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_body_fbumper_carpaint_2_EXT_carpaint6_0.geometry} material={materials['EXT_carpaint.2']} />
                        </group>
                        <group position={[0, -65.97, -220.18]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_body_fbumper_SUB6_EXT_chrome_blue1_0.geometry} material={materials['EXT_chrome_blue.3']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_body_fbumper_SUB0_EXT_chrome_blue2_0.geometry} material={materials['EXT_chrome_blue.3']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_body_fbumper_SUB2_EXT_metal1_0.geometry} material={materials['EXT_metal.1']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_body_fbumper_SUB5_EXT_carbonfiber_0.geometry} material={materials.EXT_carbonfiber} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_body_fbumper_SUB4_EXT_chrome4_0.geometry} material={materials['EXT_headlight_chrome.6_1']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_body_fbumper_SUB3_EXT_plastic13_0.geometry} material={materials['EXT_plastic.11']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_body_fbumper_SUB1_EXT_underside3_0.geometry} material={materials['INT_speaker_metal.2']} />
                        </group>
                        <group position={[0, -65.97, -220.18]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_body_fbumper_grille_2_EXT_front_grille1_0.geometry} material={materials.EXT_front_grille1} />
                        </group>
                    </group>
                    <group position={[80.45, 35.33, 166.61]}>
                        <group rotation={[-1.65, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_caliperLF_2_EXT_caliper_0.geometry} material={materials['EXT_caliper.1']} />
                        </group>
                    </group>
                    <group position={[83.41, 35.69, -149.5]}>
                        <group rotation={[1.65, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_caliperLR_2_EXT_caliper1_0.geometry} material={materials['EXT_caliper.1']} />
                        </group>
                    </group>
                    <group position={[-80.45, 35.33, 166.61]}>
                        <group rotation={[-1.65, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_caliperRF_2_EXT_caliper2_0.geometry} material={materials['EXT_caliper.1']} />
                        </group>
                    </group>
                    <group position={[-83.41, 35.69, -149.5]}>
                        <group rotation={[1.65, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_caliperRR_2_EXT_caliper3_0.geometry} material={materials['EXT_caliper.1']} />
                        </group>
                    </group>
                    <group position={[80.45, 35.33, 166.61]}>
                        <mesh castShadow receiveShadow geometry={nodes.GEO_RimBlur_LF_SUB1_EXT_chrome_blue3_0.geometry} material={materials['EXT_chrome_blue.3']} />
                        <mesh castShadow receiveShadow geometry={nodes.GEO_RimBlur_LF_SUB0_EXT_rim_0.geometry} material={materials['EXT_rim.1_0']} />
                        <group rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_rimLF_SUB1_EXT_chrome_blue4_0.geometry} material={materials['EXT_chrome_blue.3']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_rimLF_SUB0_EXT_rim1_0.geometry} material={materials['EXT_rim.1_0']} />
                        </group>
                        <group rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_tyreLF_2_EXT_tyre_0.geometry} material={materials['EXT_tyre.2_0']} />
                        </group>
                    </group>
                    <group position={[80.45, 35.33, 166.61]}>
                        <group rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_discLF_2_EXT_disc_0.geometry} material={materials['EXT_disc.1']} />
                        </group>
                    </group>
                    <group position={[83.41, 35.69, -149.5]}>
                        <group position={[-0.18, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_RimBlur_LR_SUB1_EXT_chrome_blue5_0.geometry} material={materials['EXT_chrome_blue.3']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_RimBlur_LR_SUB0_EXT_rim2_0.geometry} material={materials['EXT_rim.1_0']} />
                        </group>
                        <group rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_rimLR_SUB1_EXT_chrome_blue6_0.geometry} material={materials['EXT_chrome_blue.3']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_rimLR_SUB0_EXT_rim3_0.geometry} material={materials['EXT_rim.1_0']} />
                        </group>
                        <group position={[-2.73, 0, 0]} rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_tyreLR_2_EXT_tyre1_0.geometry} material={materials['EXT_tyre.2_0']} />
                        </group>
                    </group>
                    <group position={[83.41, 35.69, -149.5]}>
                        <group rotation={[-Math.PI / 2, 0, 0]} scale={0.95}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_discLR_2_EXT_disc1_0.geometry} material={materials['EXT_disc.1']} />
                        </group>
                    </group>
                    <group position={[-80.45, 35.33, 166.61]}>
                        <group position={[160.9, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_RimBlur_RF_SUB1_EXT_chrome_blue7_0.geometry} material={materials['EXT_chrome_blue.3']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_RimBlur_RF_SUB0_EXT_rim4_0.geometry} material={materials['EXT_rim.1_0']} />
                        </group>
                        <group rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_rimRF_SUB1_EXT_chrome_blue8_0.geometry} material={materials['EXT_chrome_blue.3']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_rimRF_SUB0_EXT_rim5_0.geometry} material={materials['EXT_rim.1_0']} />
                        </group>
                        <group rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_tyreRF_2_EXT_tyre2_0.geometry} material={materials['EXT_tyre.2_0']} />
                        </group>
                    </group>
                    <group position={[-80.45, 35.33, 166.61]}>
                        <group rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_discRF_2_EXT_disc2_0.geometry} material={materials['EXT_disc.1']} />
                        </group>
                    </group>
                    <group position={[-83.41, 35.69, -149.5]}>
                        <group position={[166.64, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_RimBlur_RR_SUB1_EXT_chrome_blue9_0.geometry} material={materials['EXT_chrome_blue.3']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_RimBlur_RR_SUB0_EXT_rim6_0.geometry} material={materials['EXT_rim.1_0']} />
                        </group>
                        <group rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_rimRR_SUB1_EXT_chrome_blue10_0.geometry} material={materials['EXT_chrome_blue.3']} />
                            <mesh castShadow receiveShadow geometry={nodes.GEO_rimRR_SUB0_EXT_rim7_0.geometry} material={materials['EXT_rim.1_0']} />
                        </group>
                        <group rotation={[-Math.PI / 2, 0, 0]}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_tyreRR_2_EXT_tyre3_0.geometry} material={materials['EXT_tyre.2_0']} />
                        </group>
                    </group>
                    <group position={[-83.41, 35.69, -149.5]}>
                        <group rotation={[-Math.PI / 2, 0, 0]} scale={0.95}>
                            <mesh castShadow receiveShadow geometry={nodes.GEO_discRR_2_EXT_disc3_0.geometry} material={materials['EXT_disc.1']} />
                        </group>
                    </group>
                    <group position={[83.54, 35.46, 166.64]}>
                        <mesh castShadow receiveShadow geometry={nodes.GEO_Wheel_Hub_LF_2_EXT_underside4_0.geometry} material={materials['INT_speaker_metal.2']} />
                    </group>
                    <group position={[74.41, 35.46, 166.64]}>
                        <mesh castShadow receiveShadow geometry={nodes.GEO_Wheel_Hub_RF_2_EXT_underside5_0.geometry} material={materials['INT_speaker_metal.2']} />
                    </group>
                    <group position={[0, 0, -13.46]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.GEO_brakelight_2_EXT_brakelight_0.geometry} material={materials.EXT_brakelight} />
                    </group>
                    <group position={[0, 0, 14.45]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.GEO_headlight_glass_2_EXT_headlight_glass3_0.geometry} material={materials.EXT_headlight_glass} />
                    </group>
                    <group position={[0, 0, 14.45]} rotation={[-Math.PI / 2, 0, 0]}>
                        <mesh castShadow receiveShadow geometry={nodes.GEO_rearlight_glass_2_EXT_rearlight_glass2_0.geometry} material={materials['EXT_rearlight_glass.1']} />
                    </group>
                </group>
            </group>
        </group>

    )
}

useGLTF.preload('../../public/models/car/model-transformed.glb')
